In [48]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [ ]:
def check_(x, y):
    if point_matrix_check(x, y, matrix):
        return False
    if matrix[x][y] != 0:
        return False
    else:
        return True

def check(x, y):
    if check_(x+1,y-1) & check_(x+2,y) & check_(x+1,y+1):
        return 'down'
    elif check_(x, y-2) & check_(x-1, y-1) & check_(x+1, y-1) & check_(x+1,y-2) & check_(x+2, y-1):
        return 'left_down'
    elif check_(x-1,y+1) & check_(x,y+2) & check_(x+1,y+1) & check_(x+1,y+2) & check_(x+2,y+1):
        return 'right_down'
    else:
        return 'no'

def point_matrix_check(x, y, matrix):
    if x < 0 or x >= len(matrix) or y < 0 or y >= len(matrix[0]):
        return True
    else:
        return False
        
def matrix_check(x, y, matrix):
    if x < 0 or x >= len(matrix) - 1 or y < 1 or y >= len(matrix[0]) - 1:
        return True
    else:
        return False

def print_matrix(center, idx, prev_center=None):
    global matrix
    if prev_center:
        matrix[prev_center[0]][prev_center[1]] = 0
        for dx, dy in zip([-1,0,1,0],[0,-1,0,1]):
            matrix[prev_center[0]+dx][prev_center[1]+dy] = 0
    matrix[center[0]][center[1]] = idx+1
    for dx, dy in zip([-1,0,1,0],[0,-1,0,1]):
        if point_matrix_check(center[0]+dx, center[1]+dy, matrix):
            continue
        matrix[center[0]+dx][center[1]+dy] = idx+1

def gol_move(gol_dict, idx):
    global exit_list
    curr_center = gol_dict[idx]['center']
    print_matrix(curr_center, idx)
    while True:
        if matrix_check(curr_center[0], curr_center[1], matrix):
            break
        check_down = check(curr_center[0], curr_center[1])
        curr_center_ = curr_center
        if check_down == 'down':            
            curr_center = [curr_center[0]+1, curr_center[1]]
        elif check_down == 'left_down':
            curr_center = [curr_center[0]+1, curr_center[1]-1]
            gol_dict[idx]['exit'] = exit_list[exit_list.index(gol_dict[idx]['exit']) - 1]
        elif check_down == 'right_down':
            curr_center = [curr_center[0]+1, curr_center[1]+1]
            idx_ = exit_list.index(gol_dict[idx]['exit']) + 1
            if idx_ >= len(exit_list):
                idx_ = 0
            gol_dict[idx]['exit'] = exit_list[idx_]
        elif check_down == 'no':
            break
        print_matrix(curr_center, idx, curr_center_)
    gol_dict[idx]['center'] = [curr_center[0], curr_center[1]]
    return gol_dict

def move(gol_dict, idx):
    curr_center = gol_dict[idx]['center']
    visited = [[False] * len(matrix[0]) for _ in range(len(matrix))]
    visited[0:3] = [[True]*len(matrix[0])] * 3
    queue = []
    queue.append([curr_center[0], curr_center[1]])
    curr_row = curr_center[0]
    while queue:
        row, col = queue.pop()
        if idx == 3:
            print(row, col)
        # if row == 7 and col == 3:
        #     print('found')
        if visited[row][col]:
            continue        
        visited[row][col] = True
        
        for dx, dy in zip([-1,0,1,0], [0,-1,0,1]):
            if point_matrix_check(row+dx, col+dy, matrix):
                continue
            if matrix[row+dx][col+dy] == 0:
                continue
            gol_exit = gol_dict[matrix[row][col]-1]['exit']
            gol_center = gol_dict[matrix[row][col]-1]['center']
            curr_exit = [gol_center[0] + gol_exit[0], gol_center[1] + gol_exit[1]]
            if matrix[row+dx][col+dy] != matrix[row][col]:
                next_gol_exit = gol_dict[matrix[row+dx][col+dy]-1]['exit']
                next_gol_center = gol_dict[matrix[row+dx][col+dy]-1]['center']
                next_exit = [next_gol_center[0] + next_gol_exit[0], next_gol_center[1] + next_gol_exit[1]]
                if (curr_exit[0] == row and curr_exit[1] == col) and (next_exit[0] != row + dx or next_exit[1] != col + dy):
                    queue.append([row+dx, col+dy])
            elif matrix[row+dx][col+dy] == matrix[row][col]:
                queue.append([row+dx, col+dy])
        if curr_row < row:
            curr_row = row
    return curr_row

import numpy as np

R, C, K = 6, 5, 6
col_list = [2, 2, 4, 2, 2, 2]
out_dir_list = [3, 0, 2, 0, 0, 2]

# R, C, K = 7, 9, 6
# col_list = [4, 5, 2, 8, 2, 6]
# out_dir_list = [1, 1, 1, 1, 2, 0]

# R, C, K = map(int, input().split())
exit_list = [[-1, 0], [0, 1], [1, 0], [0, -1]]
output = 0
idx = 0
gol_dict = []
pos = -1
matrix = [[0] * C for _ in range(R+3)]
for glo_idx, _ in enumerate(range(K)):
    # col_, out_dir = map(int, input().split())
    col_, out_dir = col_list[glo_idx], out_dir_list[glo_idx]
    if out_dir == 0: out_dir = [-1, 0]
    elif out_dir == 1: out_dir = [0, 1]
    elif out_dir == 2: out_dir = [1, 0]
    elif out_dir == 3: out_dir = [0, -1]
    gol_dict.append({'center': [1, col_-1], 'exit': out_dir})
    gol_dict = gol_move(gol_dict, idx)
    pos = move(gol_dict, idx)
    print(np.array(matrix))
    if (pos-2) <= 0:
        gol_dict = []
        matrix = [[0] * C for _ in range(R+3)]
        pos = 2
        idx = -1
    idx += 1
    output += pos-2
    print(pos-2, 'idx:', idx)
    print(gol_dict)
print(output)

In [33]:
import numpy as np

# r, c, k = map(int, input().split())
# golem = [list(map(int, input().split())) for _ in range(k)]
r, c, k = 6, 5, 6
golem = [[2, 3], [2, 0], [4, 2], [2, 0], [0, 0], [2, 2]]

# 격자 밖으로 나가면 안됨 / 인덱스가 1로 시작 -> 격자 밖(y)을 벽으로 둘러쌈
# 골렘이 격자에 입장하기 전 밖에 있는 모습을 표현하기 위해 x값을 늘려줌 -> 3칸늘림
board = [[1] + [0]*c + [1] for _ in range(r+3)] + [[1]*(c+2)]
print(np.array(board))

# 방향 -> 북동남서(시계)
dx = [-1, 0, 1, 0]
dy = [0, 1, 0, -1]

exits = []  # 골렘 출구를 저장
cnt = 2     # 0: 빈칸, 1: 벽, 2이상: 골렘
result = 0  # 누저 값

# k개의 정령 이동
for in_y, di in golem:
    # 골렘 이동
    x, y , di = move_golem(in_y, di)

    # 골렘이 밖으로 튀어 나갔는지 확인
    if is_board(x):
        # 격자를 초기화
        board = [[1] + [0]*c + [1] for _ in range(r+3)] + [[1]*(c+2)]
        cnt = 2     # 골렘 다 치우기
        exits = []  # 출구 비우기
        continue    # 다음 정령 탐색

    # 골렘 격자에 위치 시키기
    set_golem(x, y, di)

    # 정령 이동
    result += move_elf(x, y)
    print(np.array(board))
print(result)

[[1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]
[[1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 2 0 0 0 1]
 [1 2 2 2 0 0 1]
 [1 0 2 0 0 0 1]
 [1 1 1 1 1 1 1]]
[[1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 3 0 1]
 [1 0 2 3 3 3 1]
 [1 2 2 2 3 0 1]
 [1 0 2 0 0 0 1]
 [1 1 1 1 1 1 1]]
[[1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 4 0 0 1]
 [1 0 4 4 4 0 1]
 [1 0 0 4 3 0 1]
 [1 0 2 3 3 3 1]
 [1 2 2 2 3 0 1]
 [1 0 2 0 0 0 1]
 [1 1 1 1 1 1 1]]
[[1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 2 0 0 0 1]
 [1 2 2 2 0 0 1]
 [1 0 2 0 0 0 1]
 [1 1 1 1 1 1 1]]
[[1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 3 0 1]
 [1 0 2 3 3 3 1]
 [1 2 2 2 3 0 1]
 [1 0 2 0

In [1]:
def check_(x, y):
    if point_matrix_check(x, y, matrix):
        return False
    if matrix[x][y] != 0:
        return False
    else:
        return True

def check(x, y):
    if check_(x+1,y-1) and check_(x+2,y) and check_(x+1,y+1):
        return 'down'
    elif check_(x, y-2) and check_(x-1, y-1) and check_(x+1, y-1) and check_(x+1,y-2) and check_(x+2, y-1):
        return 'left_down'
    elif check_(x-1,y+1) and check_(x,y+2) and check_(x+1,y+1) and check_(x+1,y+2) and check_(x+2,y+1):
        return 'right_down'
    else:
        return 'no'

def point_matrix_check(x, y, matrix):
    if x < 0 or x >= len(matrix) or y < 0 or y >= len(matrix[0]):
        return True
    else:
        return False
        
def matrix_check(x, y, matrix):
    if x < 0 or x >= len(matrix) - 1 or y < 1 or y >= len(matrix[0]) - 1:
        return True
    else:
        return False

def print_matrix(center, idx, prev_center=None):
    global matrix
    if prev_center:
        matrix[prev_center[0]][prev_center[1]] = 0
        for dx, dy in zip([-1,0,1,0],[0,-1,0,1]):
            matrix[prev_center[0]+dx][prev_center[1]+dy] = 0
    matrix[center[0]][center[1]] = idx+1
    for dx, dy in zip([-1,0,1,0],[0,-1,0,1]):
        if point_matrix_check(center[0]+dx, center[1]+dy, matrix):
            continue
        matrix[center[0]+dx][center[1]+dy] = idx+1

def gol_move(gol_dict, idx):
    global exit_list
    curr_center = gol_dict[idx]['center']
    # print_matrix(curr_center, idx)
    while True:
        if matrix_check(curr_center[0], curr_center[1], matrix):
            break
        check_down = check(curr_center[0], curr_center[1])
        curr_center_ = curr_center
        if check_down == 'down':            
            curr_center = [curr_center[0]+1, curr_center[1]]
        elif check_down == 'left_down':
            curr_center = [curr_center[0]+1, curr_center[1]-1]
            gol_dict[idx]['exit'] = exit_list[exit_list.index(gol_dict[idx]['exit']) - 1]
        elif check_down == 'right_down':
            curr_center = [curr_center[0]+1, curr_center[1]+1]
            idx_ = exit_list.index(gol_dict[idx]['exit']) + 1
            if idx_ >= len(exit_list):
                idx_ = 0
            gol_dict[idx]['exit'] = exit_list[idx_]
        elif check_down == 'no':
            break
        print_matrix(curr_center, idx, curr_center_)
    gol_dict[idx]['center'] = [curr_center[0], curr_center[1]]
    return gol_dict

def move(gol_dict, idx):
    curr_center = gol_dict[idx]['center']
    visited = [[False] * len(matrix[0]) for _ in range(len(matrix))]
    # visited[0:3] = [[True]*len(matrix[0])] * 3
    visited[0] = [True] * len(matrix[0])
    queue = []
    queue.append([curr_center[0], curr_center[1]])
    visited[curr_center[0]][curr_center[1]] = True
    curr_row = curr_center[0]
    while queue:
        row, col = queue.pop()
        if idx == 3:
            print(row, col)
        # if row == 7 and col == 3:
        #     print('found')
        if visited[row][col]:
            continue        
        
        for dx, dy in zip([-1,0,1,0], [0,-1,0,1]):
            if point_matrix_check(row+dx, col+dy, matrix):
                continue
            if matrix[row+dx][col+dy] == 0:
                continue
            gol_exit = gol_dict[matrix[row][col]-1]['exit']
            gol_center = gol_dict[matrix[row][col]-1]['center']
            curr_exit = [gol_center[0] + gol_exit[0], gol_center[1] + gol_exit[1]]
            if matrix[row+dx][col+dy] != matrix[row][col]:
                next_gol_exit = gol_dict[matrix[row+dx][col+dy]-1]['exit']
                next_gol_center = gol_dict[matrix[row+dx][col+dy]-1]['center']
                next_exit = [next_gol_center[0] + next_gol_exit[0], next_gol_center[1] + next_gol_exit[1]]
                if (curr_exit[0] == row and curr_exit[1] == col) and (next_exit[0] != row + dx or next_exit[1] != col + dy):
                    queue.append([row+dx, col+dy])
                    visited[row][col] = True
            elif matrix[row+dx][col+dy] == matrix[row][col]:
                queue.append([row+dx, col+dy])
                visited[row][col] = True
        if curr_row < row:
            curr_row = row
    return curr_row

In [ ]:

import numpy as np

R, C, K = 6, 5, 6
col_list = [2, 2, 4, 2, 2, 2]
out_dir_list = [3, 0, 2, 0, 0, 2]

# R, C, K = 7, 9, 6
# col_list = [4, 5, 2, 8, 2, 6]
# out_dir_list = [1, 1, 1, 1, 2, 0]

# R, C, K = map(int, input().split())
exit_list = [[-1, 0], [0, 1], [1, 0], [0, -1]]
output = 0
idx = 0
gol_dict = []
pos = -1
matrix = [[0] * C for _ in range(R+3)]
for glo_idx, _ in enumerate(range(K)):
    # col_, out_dir = map(int, input().split())
    col_, out_dir = col_list[glo_idx], out_dir_list[glo_idx]
    if out_dir == 0: out_dir = [-1, 0]
    elif out_dir == 1: out_dir = [0, 1]
    elif out_dir == 2: out_dir = [1, 0]
    elif out_dir == 3: out_dir = [0, -1]
    gol_dict.append({'center': [1, col_-1], 'exit': out_dir})
    gol_dict = gol_move(gol_dict, idx)
    pos = move(gol_dict, idx)
    print(np.array(matrix))
    if (pos-2) <= 0:
        gol_dict = []
        matrix = [[0] * C for _ in range(R+3)]
        pos = 2
        idx = -1
    idx += 1
    output += pos-2
    print(pos-2, 'idx:', idx)
    print(gol_dict)
print(output)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [1 1 1 0 0]
 [0 1 0 0 0]]
5 idx: 1
[{'center': [7, 1], 'exit': [0, -1]}]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 2 0]
 [0 1 2 2 2]
 [1 1 1 2 0]
 [0 1 0 0 0]]
4 idx: 2
[{'center': [7, 1], 'exit': [0, -1]}, {'center': [6, 3], 'exit': [1, 0]}]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 3 0 0]
 [0 3 3 3 0]
 [0 0 3 2 0]
 [0 1 2 2 2]
 [1 1 1 2 0]
 [0 1 0 0 0]]
2 idx: 3
[{'center': [7, 1], 'exit': [0, -1]}, {'center': [6, 3], 'exit': [1, 0]}, {'center': [4, 2], 'exit': [0, 1]}]
2 1
[[0 0 0 0 0]
 [0 4 0 0 0]
 [4 4 4 0 0]
 [0 4 3 0 0]
 [0 3 3 3 0]
 [0 0 3 2 0]
 [0 1 2 2 2]
 [1 1 1 2 0]
 [0 1 0 0 0]]
0 idx: 0
[]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [1 1 1 0 0]
 [0 1 0 0 0]]
5 idx: 1
[{'center': [7, 1], 'exit': [-1, 0]}]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 2 0]
 [0 1 2 2 2]
 [1 1 1